import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const dgKeys=[1,2,3].map(i=>Deno.env.get(`DEEPGRAM_API_KEY_${i}`)).filter((v):v is string=>!!v?.trim());
const sxKeys=[1,2,3,4].map(i=>Deno.env.get(`SONIOX_API_KEY_${i}`)).filter((v):v is string=>!!v?.trim());let dgCursor=0,sxCursor=0;
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const pick=(l:string,t:string)=>{l=l.toLowerCase().trim();return l==="urdu"||l==="roman urdu"||(l==="auto"&&/[\u0600-\u06ff]/u.test(t))?"soniox":"deepgram" as const};
async function deepgram(text:string){if(!dgKeys.length)throw Error("Deepgram TTS is not configured");let status=502;for(let a=0;a<dgKeys.length;a++){const i=(dgCursor+a)%dgKeys.length;const r=await fetch("https://api.deepgram.com/v1/speak?model=aura-2-thalia-en",{method:"POST",headers:{Authorization:`Token ${dgKeys[i]}`,"Content-Type":"application/json"},body:JSON.stringify({text})});if(r.ok){dgCursor=i;return{provider:"deepgram",mimeType:r.headers.get("content-type")??"audio/mpeg",bytes:new Uint8Array(await r.arrayBuffer())}}status=r.status;if(![401,402,403,429].includes(status))break}throw Error(`Deepgram TTS failed (${status})`)}
async function soniox(text:string){if(!sxKeys.length)throw Error("Soniox TTS is not configured");let status=502;for(let a=0;a<sxKeys.length;a++){const i=(sxCursor+a)%sxKeys.length;const r=await fetch("https://tts-rt.soniox.com/tts",{method:"POST",headers:{Authorization:`Bearer ${sxKeys[i]}`,"Content-Type":"application/json"},body:JSON.stringify({model:"tts-rt-v2",language:"ur",voice:"Daniel",audio_format:"mp3",text,speed:1,reduce_silence:true})});if(r.ok){sxCursor=i;return{provider:"soniox",mimeType:r.headers.get("content-type")??"audio/mpeg",bytes:new Uint8Array(await r.arrayBuffer())}}status=r.status;if(![401,402,403,429].includes(status))break}throw Error(`Soniox TTS failed (${status})`)}
function b64(x:Uint8Array){let s="";for(let i=0;i<x.length;i+=0x8000)s+=String.fromCharCode(...x.subarray(i,Math.min(i+0x8000,x.length)));return btoa(s)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(!req.headers.get("Authorization")?.startsWith("Bearer "))return out({error:"Unauthorized"},401);const body=await req.json();const rawText=typeof body?.text==="string"?body.text.trim():"";const language=typeof body?.language==="string"?body.language:"auto";if(!rawText)return out({error:"Text is required"},400);const text=rawText.replace(/[\u0900-\u097F]+/gu," ").replace(/\s{2,}/g," ").trim();if(!text)return out({error:"No supported speech text remains after validation"},400);if(["hindi","hi"].includes(language.toLowerCase().trim()))return out({error:"Unsupported speech language"},400);const r=pick(language,text)==="soniox"?await soniox(text):await deepgram(text);return out({provider:r.provider,mimeType:r.mimeType,audioBase64:b64(r.bytes)})}catch(e){console.error(e);return out({error:e instanceof Error?e.message:"Speech synthesis failed"},503)}});
