import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:provider/provider.dart';
import '../providers/providers.dart';
import '../theme/app_theme.dart';
import '../models/models.dart';
import '../widgets/reusable_widgets.dart';
import '../widgets/speakable_caption_bubble.dart';
import '../l10n/app_strings.dart';

class SessionDetailScreen extends StatefulWidget { final String sessionId; const SessionDetailScreen({super.key,required this.sessionId}); @override State<SessionDetailScreen> createState()=>_SessionDetailScreenState(); }
class _SessionDetailScreenState extends State<SessionDetailScreen>{
 @override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_){final p=context.read<ProfessionalProvider>();if(p.getInsightForSession(widget.sessionId)==null)p.generateInsights(widget.sessionId);});}
 @override Widget build(BuildContext context){final p=context.watch<ProfessionalProvider>();final x=p.sessions.where((s)=>s.id==widget.sessionId).firstOrNull;final s=AppStrings.of(context);if(x==null)return const Scaffold(body:Center(child:Text('Session is no longer available.')));final i=p.getInsightForSession(widget.sessionId);return DefaultTabController(length:4,child:Scaffold(appBar:AppBar(title:Text(x.title),bottom:TabBar(isScrollable:true,tabs:[Tab(text:s.overviewTab),Tab(text:s.transcriptTab),Tab(text:s.summaryTab),Tab(text:s.actionsTab)]),actions:[PopupMenuButton<String>(itemBuilder:(_)=>[PopupMenuItem(value:'export',child:Text(s.exportAction)),PopupMenuItem(value:'delete',child:Text(s.deleteAction))],onSelected:(v){if(v=='export')_showExport(context,x,i,s);else _confirmDelete(context,x,s);})]),body:TabBarView(children:[_overview(context,x,i,s),_transcript(context,x,s),_summary(context,i,s),_actions(context,i,s)])));}
 Widget _overview(BuildContext c,ProfessionalSession x,ProfessionalInsight? i,AppStrings s)=>SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.title,style:Theme.of(c).textTheme.headlineMedium),const SizedBox(height:12),_row(c,'Type',x.type.name.toUpperCase()),_row(c,'Date','${x.createdAt.day}/${x.createdAt.month}/${x.createdAt.year}'),_row(c,'Captions','${x.captions.length}'),_row(c,'Language',x.captionLanguage),_row(c,'Retention','${x.retentionDays} days'),Row(children:[const Icon(Icons.timer,size:16),const SizedBox(width:8),RetentionBadge(daysRemaining:x.daysRemaining)])])),),PrivacyNotice(text:s.savedRecordsNote),if(i?.isAvailable==true)...[const SizedBox(height:16),_summaryCard(c,i!,s)]]));
 Widget _row(BuildContext c,String l,String v)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Row(children:[Expanded(child:Text(l,style:Theme.of(c).textTheme.bodySmall)),Flexible(child:Text(v,style:Theme.of(c).textTheme.bodyMedium))]));
 Widget _transcript(BuildContext c,ProfessionalSession x,AppStrings s){if(x.captions.isEmpty)return EmptyState(icon:Icons.subtitles_off,title:s.noTranscriptAvailable,subtitle:s.noTranscriptDesc);final settings=context.read<SettingsProvider>();return ListView.builder(padding:const EdgeInsets.all(16),itemCount:x.captions.length,itemBuilder:(c,i){final cap=x.captions[i];return Padding(padding:const EdgeInsets.only(bottom:14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${cap.speaker} · ${cap.timestamp.hour.toString().padLeft(2,'0')}:${cap.timestamp.minute.toString().padLeft(2,'0')}',style:Theme.of(c).textTheme.bodySmall?.copyWith(fontWeight:FontWeight.w600)),const SizedBox(height:4),SpeakableCaptionBubble(caption:cap,textSize:settings.captionTextSize,isHighContrast:settings.isHighContrast)]));});}
 Widget _summary(BuildContext c,ProfessionalInsight? i,AppStrings s){if(i==null||!i.isAvailable)return ErrorState(title:s.insightsUnavailable,message:s.insightsUnavailableDesc,buttonText:s.viewTranscript);return SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const AiDisclaimer(),const SizedBox(height:12),_summaryCard(c,i,s),if(i.actionItems.isNotEmpty)...[const SizedBox(height:16),InsightCard(title:s.actionItems,icon:Icons.check_circle_outline,items:i.actionItems,iconColor:AppTheme.secondaryLight)],if(i.deadlines.isNotEmpty)...[const SizedBox(height:8),InsightCard(title:s.deadlines,icon:Icons.schedule,items:i.deadlines,iconColor:AppTheme.warningLight)],if(i.mentionedPeople.isNotEmpty)...[const SizedBox(height:8),InsightCard(title:s.peopleMentioned,icon:Icons.people_outline,items:i.mentionedPeople)] ]));}
 Widget _summaryCard(BuildContext c,ProfessionalInsight i,AppStrings s)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.auto_awesome,size:16),const SizedBox(width:8),Text(s.aiSummary,style:Theme.of(c).textTheme.titleMedium)]),const SizedBox(height:12),if(i.summaryBullets.isEmpty)Text(i.summary) else ...i.summaryBullets.map((b)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('•  '),Expanded(child:Text(b))]))),const AiDisclaimer()])));
 Widget _actions(BuildContext c,ProfessionalInsight? i,AppStrings s){if(i==null||i.actionItems.isEmpty)return EmptyState(icon:Icons.task_alt,title:s.noActionItems,subtitle:s.noActionItemsDesc);return SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(children:[InsightCard(title:s.actionItems,icon:Icons.task_alt,items:i.actionItems,iconColor:AppTheme.secondaryLight),if(i.deadlines.isNotEmpty)...[const SizedBox(height:16),InsightCard(title:s.deadlines,icon:Icons.schedule,items:i.deadlines,iconColor:AppTheme.warningLight)],if(i.mentionedPeople.isNotEmpty)...[const SizedBox(height:16),InsightCard(title:s.peopleMentioned,icon:Icons.people_outline,items:i.mentionedPeople)]]));}
 void _showExport(BuildContext c,ProfessionalSession x,ProfessionalInsight? i,AppStrings s)=>showDialog(context:c,builder:(ctx)=>AlertDialog(title:Text(s.exportAction),content:Column(mainAxisSize:MainAxisSize.min,children:[PrivacyNotice(text:s.exportPrivacyNote),ListTile(leading:const Icon(Icons.text_snippet),title:Text(s.exportTxt),onTap:(){Navigator.pop(ctx);_exportTxt(x,i,c);}),ListTile(leading:const Icon(Icons.copy),title:Text(s.copyClipboard),onTap:()async{Navigator.pop(ctx);await Clipboard.setData(ClipboardData(text:_exportText(x,i)));if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Copied to clipboard')));})]));
 String _exportText(ProfessionalSession x,ProfessionalInsight? i){final b=StringBuffer('HumSukhan — Session Export\n\nTitle: ${x.title}\nType: ${x.type.name}\nLanguage: ${x.captionLanguage}\n\n--- TRANSCRIPT ---\n');for(final cap in x.captions)b.writeln('${cap.speaker}: ${cap.text}');if(i?.isAvailable==true){b.writeln('\n--- AI SUMMARY ---');for(final bullet in i!.summaryBullets)b.writeln('• $bullet');if(i.actionItems.isNotEmpty){b.writeln('\nAction Items:');for(final a in i.actionItems)b.writeln('• $a');}if(i.deadlines.isNotEmpty){b.writeln('\nDeadlines:');for(final d in i.deadlines)b.writeln('• $d');}}return b.toString();}
 Future<void> _exportTxt(ProfessionalSession x,ProfessionalInsight? i,BuildContext c)async{try{final dir=await getApplicationDocumentsDirectory();final file=File('${dir.path}/humsukhan_${x.id}.txt');await file.writeAsString(_exportText(x,i));await Share.shareXFiles([XFile(file.path)],text:'HumSukhan session export');}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('Export failed: $e')));}}
 void _confirmDelete(BuildContext c,ProfessionalSession x,AppStrings s)=>showDialog(context:c,builder:(ctx)=>AlertDialog(title:Text(s.deleteSessionConfirm),content:Text(s.deleteSessionDesc),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:Text(s.cancel)),TextButton(onPressed:(){context.read<ProfessionalProvider>().deleteSession(x.id);Navigator.pop(ctx);Navigator.pop(c);},child:Text(s.delete,style:TextStyle(color:Theme.of(ctx).colorScheme.error))) ]));
}
